version: "3"
services:
    mongo:
        image: "mongo:latest"
        ports:
            - "27017:27017"
        logging:
            driver: none
    myreader:
        build: .
        depends_on:
            - mongo
        ports:
            - "5000:5000"