version: "3"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  #   depends_on:
  #     - mongodb
  #   links:
  #     - mongodb

  # mongodb:
  #     image: mongo:latest
  #     # ports:
  #     #   - 2717:27017
  #     # volumes:
  #     #   - data:/data/db