version: "3.7"
services:
  db: 
    image: mongo
    container_name: mymongo
    volumes:
      - ./app/db
    restart: always
  api:
    build: "./"
    container_name: api
    restart: always
    volumes: 
      - ./app 
    ports:
      - "3333:3333"
    depends_on:
      - db