version: '3'

services:
  api:
    build: .
    ports:
      - '5000:5000'
    #links:
    #  - db
    networks:
      - api-db-network

  db:
    image: mongo
    env_file: .env.database
    ports:
      - '27017:27017'
    volumes:
      - db_data:/data/db
    networks:
      - api-db-network

volumes:
  db_data: {}

networks:
  api-db-network:
    driver: bridge
