app_clients:
  build: "./clients_api"
  command: python -u ./clients_api/app.py
  ports:
    - "${CLIENTS_API_PORT}:${CLIENTS_API_PORT}"
  volumes:
    - .:/app
  links:
    - db
app_taxas:
  build: "./taxas_api"
  command: python -u ./taxas_api/app.py
  ports:
    - "${TAXAS_API_PORT}:${TAXAS_API_PORT}"
  volumes:
    - .:/app
  links:
    - db
app_calculo:
  build: "./calculo_api"
  command: python -u ./calculo_api/app.py
  ports:
    - "${CALCULO_API_PORT}:${CALCULO_API_PORT}"
  volumes:
    - .:/app
  links:
    - db
db:
  image: mongo:latest
  hostname: desafio_mongodb
  environment:
    - MONGO_INITDB_DATABASE=desafio_bd
    - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
    - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
  ports:
    - '27017:27017'
