# Generated by Django 3.0.5 on 2021-02-19 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Taxas',
        ),
    ]
